Vagrant.configure("2") do |config|

	config.vm.define "ansible" do |ansible|
	  ansible.vm.box = "generic/ubuntu2004"
	  ansible.vm.network "private_network", ip: "10.10.20.3"
	  ansible.vm.provider "virtualbox" do |vb|
		vb.memory = 4096
		vb.cpus = 2
	  end
	end
  
	config.vm.define "client1" do |client1|
	  client1.vm.box = "generic/ubuntu2004"
	  client1.vm.network "private_network", ip: "10.10.20.4"
	  client1.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
	  end
	end
  
	config.vm.define "client2" do |client2|
	  client2.vm.box = "generic/ubuntu2004"
	  client2.vm.network "private_network", ip: "10.10.20.5"
	  client2.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
	  end
	end
  
  end