
Vagrant.configure("2") do |config|

config.vm.box = "debian/bullseye64"

config.vm.provision "file", source: "index.html", destination:"index.html"
config.vm.provision "shell", inline: "apt-get update"
config.vm.provision "shell", inline: "apt-get install -y nginx"
config.vm.network "forwarded_port", guest: 80, host: 80
config.vm.synced_folder "/home/user/tp-r504/tp5/vag2/", "/home/vagrant"

end
