name: Tests de validation regex

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Installer pytest
      run: python -m pip install pytest
      
    - name: Exécuter les tests
      run: |
        python -m pytest tests/
